USE [master]
GO
/****** Object:  Database [CitizenRequestsDB]    Script Date: 02.03.2025 4:10:10 ******/
CREATE DATABASE [CitizenRequestsDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CitizenRequestsDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.TDG2022\MSSQL\DATA\CitizenRequestsDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CitizenRequestsDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.TDG2022\MSSQL\DATA\CitizenRequestsDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [CitizenRequestsDB] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CitizenRequestsDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CitizenRequestsDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [CitizenRequestsDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CitizenRequestsDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CitizenRequestsDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CitizenRequestsDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CitizenRequestsDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CitizenRequestsDB] SET  MULTI_USER 
GO
ALTER DATABASE [CitizenRequestsDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CitizenRequestsDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CitizenRequestsDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CitizenRequestsDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CitizenRequestsDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CitizenRequestsDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [CitizenRequestsDB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CitizenRequestsDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CitizenRequestsDB]
GO
/****** Object:  Table [dbo].[Admins]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admins](
	[AdminId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PasswordHash] [varbinary](64) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Applications]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Applications](
	[ApplicationId] [int] IDENTITY(1,1) NOT NULL,
	[CitizenId] [int] NOT NULL,
	[CategoryId] [int] NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[SubmissionDate] [datetime] NULL,
	[ResolutionDate] [datetime] NULL,
	[Description] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ApplicationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Categories]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categories](
	[CategoryId] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[CategoryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Citizens]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Citizens](
	[CitizenId] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](255) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[PhoneNumber] [nvarchar](20) NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
	[CreatedAt] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CitizenId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PhoneNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CitizenSessions]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CitizenSessions](
	[SessionId] [int] IDENTITY(1,1) NOT NULL,
	[CitizenId] [int] NOT NULL,
	[Token] [nvarchar](255) NOT NULL,
	[CreatedAt] [datetime] NULL,
	[ExpiresAt] [datetime] NOT NULL,
	[IsActive] [bit] NULL,
	[AuthenticationScheme] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[SessionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[Token] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Responses]    Script Date: 02.03.2025 4:10:10 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Responses](
	[ResponseId] [int] IDENTITY(1,1) NOT NULL,
	[ApplicationId] [int] NOT NULL,
	[AdminId] [int] NULL,
	[ResponseText] [nvarchar](max) NOT NULL,
	[ResponseDate] [datetime] NULL,
	[IsFromCitizen] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ResponseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[Applications] ADD  DEFAULT (getdate()) FOR [SubmissionDate]
GO
ALTER TABLE [dbo].[Citizens] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[CitizenSessions] ADD  DEFAULT (getdate()) FOR [CreatedAt]
GO
ALTER TABLE [dbo].[CitizenSessions] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[Responses] ADD  DEFAULT (getdate()) FOR [ResponseDate]
GO
ALTER TABLE [dbo].[Responses] ADD  DEFAULT ((0)) FOR [IsFromCitizen]
GO
ALTER TABLE [dbo].[Applications]  WITH CHECK ADD  CONSTRAINT [FK_Applications_Categories] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Categories] ([CategoryId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Applications] CHECK CONSTRAINT [FK_Applications_Categories]
GO
ALTER TABLE [dbo].[Applications]  WITH CHECK ADD  CONSTRAINT [FK_Applications_Citizens] FOREIGN KEY([CitizenId])
REFERENCES [dbo].[Citizens] ([CitizenId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Applications] CHECK CONSTRAINT [FK_Applications_Citizens]
GO
ALTER TABLE [dbo].[CitizenSessions]  WITH CHECK ADD  CONSTRAINT [FK_CitizenSessions_Citizens] FOREIGN KEY([CitizenId])
REFERENCES [dbo].[Citizens] ([CitizenId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[CitizenSessions] CHECK CONSTRAINT [FK_CitizenSessions_Citizens]
GO
ALTER TABLE [dbo].[Responses]  WITH CHECK ADD  CONSTRAINT [FK_Responses_Admins] FOREIGN KEY([AdminId])
REFERENCES [dbo].[Admins] ([AdminId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Responses] CHECK CONSTRAINT [FK_Responses_Admins]
GO
ALTER TABLE [dbo].[Responses]  WITH CHECK ADD  CONSTRAINT [FK_Responses_Applications] FOREIGN KEY([ApplicationId])
REFERENCES [dbo].[Applications] ([ApplicationId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Responses] CHECK CONSTRAINT [FK_Responses_Applications]
GO
ALTER TABLE [dbo].[Applications]  WITH CHECK ADD CHECK  (([Status]=N'Отклонено' OR [Status]=N'Рассмотрено' OR [Status]=N'В обработке' OR [Status]=N'Новое'))
GO
USE [master]
GO
ALTER DATABASE [CitizenRequestsDB] SET  READ_WRITE 
GO
